-- ============================================================
-- MIGRATION: 20260626_schoolium_chat12_final.sql
-- Project:   Schoolium — Multi-tenant SaaS for Indian Schools
-- Session:   Chat 12
-- Date:      2026-06-26
-- Author:    Generated by Senior DB Architect review
--
-- SCOPE: Includes ONLY the final, working versions of all
--        SQL changes discussed and confirmed deployed in
--        Chat Session 12. Obsolete, failed, and superseded
--        versions have been removed.
--
-- ASSUMES: All prior session migrations already applied:
--   - 20260622_whatsapp_system_final.sql
--   - fee_part1_tables.sql   (fee_structures, fee_structure_items,
--                             fee_discounts, fee_dues, fee_payments)
--   - fee_part2_functions.sql (generate_fee_dues, record_fee_payment v1,
--                              get_defaulters, get_student_fee_ledger,
--                              get_fee_dashboard_stats,
--                              generate_fee_receipt_number)
--   - fee_part3_rls.sql      (RLS policies on all fee tables)
--
-- EXECUTION ORDER (dependency-safe):
--   1. ALTER TABLE  — students.fee_structure_id column
--   2. INDEX        — idx_students_fee_structure
--   3. FUNCTIONS    — in dependency order:
--        a. record_fee_payment()           (replaces prior version)
--        b. search_students_omnibox()      (new)
--        c. generate_fee_dues_capped()     (new — used by d, e)
--        d. auto_generate_monthly_dues()   (new — uses c)
--        e. trigger_manual_due_generation()(new — uses d)
--        f. assign_student_fee_structure() (new — uses C1 column)
--        g. get_student_billing_summary()  (new — uses C1 column)
--   4. CRON         — pg_cron job (unschedule old if exists, schedule new)
--   5. PERMISSIONS  — REVOKE/GRANT on all new/replaced functions
-- ============================================================


-- ============================================================
-- SECTION 1: SCHEMA CHANGES
-- Add fee_structure_id to students for package assignment
-- ============================================================

ALTER TABLE public.students
  ADD COLUMN IF NOT EXISTS fee_structure_id UUID
    REFERENCES public.fee_structures(id)
    ON DELETE SET NULL;

-- Partial index — only indexes rows that have a package assigned
-- Keeps index small; most students will have one assigned
CREATE INDEX IF NOT EXISTS idx_students_fee_structure
  ON public.students(fee_structure_id)
  WHERE fee_structure_id IS NOT NULL;


-- ============================================================
-- SECTION 2: REPLACE record_fee_payment()
-- Final version with 5 validation guards.
-- Supersedes the prior session version which had no validation.
-- CONFLICTS REMOVED:
--   - Prior version: no amount validation, no ownership check,
--     no method whitelist, no collector role check
--   - This version: all guards added, same signature retained
--     so all existing callers (collect page) work unchanged
-- ============================================================

CREATE OR REPLACE FUNCTION public.record_fee_payment(
  p_school_id       UUID,
  p_student_id      UUID,
  p_fee_due_id      UUID,
  p_amount_paid     NUMERIC(10,2),
  p_payment_method  TEXT,
  p_paid_date       DATE,
  p_collected_by    UUID,
  p_notes           TEXT DEFAULT NULL
)
RETURNS TABLE (payment_id UUID, receipt_number TEXT)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_receipt          TEXT;
  v_payment_id       UUID;
  v_due              RECORD;
  v_remaining        NUMERIC(10,2);
  v_new_paid         NUMERIC(10,2);
  v_new_status       TEXT;
BEGIN

  -- ── GUARD 1: amount must be positive ──────────────────────
  IF p_amount_paid IS NULL OR p_amount_paid <= 0 THEN
    RAISE EXCEPTION 'Payment amount must be greater than zero';
  END IF;

  -- ── GUARD 2: due must belong to this school + student ──────
  SELECT * INTO v_due
  FROM public.fee_dues
  WHERE id         = p_fee_due_id
    AND school_id  = p_school_id
    AND student_id = p_student_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Fee due not found or access denied';
  END IF;

  IF v_due.status = 'waived' THEN
    RAISE EXCEPTION 'Cannot collect payment on a waived due';
  END IF;

  IF v_due.status = 'paid' THEN
    RAISE EXCEPTION 'This due is already fully paid';
  END IF;

  -- ── GUARD 3: amount must not exceed remaining balance ───────
  v_remaining := v_due.total_due - v_due.amount_paid;

  IF p_amount_paid > v_remaining THEN
    RAISE EXCEPTION 'Amount paid (%) exceeds remaining balance (%)',
      p_amount_paid, v_remaining;
  END IF;

  -- ── GUARD 4: payment method must be valid ──────────────────
  IF p_payment_method NOT IN (
    'cash', 'upi', 'cheque', 'bank_transfer', 'card', 'other'
  ) THEN
    RAISE EXCEPTION 'Invalid payment method: %', p_payment_method;
  END IF;

  -- ── GUARD 5: collector must be active school_admin ─────────
  IF NOT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id        = p_collected_by
      AND school_id = p_school_id
      AND role      = 'school_admin'
      AND is_active = true
  ) THEN
    RAISE EXCEPTION 'Collector is not an active admin of this school';
  END IF;

  -- ── Generate receipt number (function from prior migration) ─
  v_receipt := public.generate_fee_receipt_number();

  -- ── Insert payment record ───────────────────────────────────
  INSERT INTO public.fee_payments (
    school_id, student_id, fee_due_id,
    amount_paid, payment_method, receipt_number,
    paid_date, collected_by, notes
  ) VALUES (
    p_school_id, p_student_id, p_fee_due_id,
    p_amount_paid, p_payment_method, v_receipt,
    p_paid_date, p_collected_by, p_notes
  )
  RETURNING id INTO v_payment_id;

  -- ── Update due status atomically ────────────────────────────
  v_new_paid   := v_due.amount_paid + p_amount_paid;
  v_new_status := CASE
    WHEN v_new_paid >= v_due.total_due THEN 'paid'
    WHEN v_new_paid > 0               THEN 'partial'
    ELSE                                   'unpaid'
  END;

  UPDATE public.fee_dues
  SET
    amount_paid = v_new_paid,
    status      = v_new_status,
    updated_at  = now()
  WHERE id = p_fee_due_id;

  RETURN QUERY SELECT v_payment_id, v_receipt;
END;
$$;


-- ============================================================
-- SECTION 3: search_students_omnibox()
-- New universal search RPC for the /collect page omnibox.
-- Searches: full_name, father_name, mother_name, parent_phone,
--           student_uid. Optional class filter. School-scoped.
-- ============================================================

CREATE OR REPLACE FUNCTION public.search_students_omnibox(
  p_school_id  UUID,
  p_query      TEXT,
  p_class_id   UUID DEFAULT NULL,
  p_limit      INT  DEFAULT 10
)
RETURNS TABLE (
  id            UUID,
  full_name     TEXT,
  student_uid   TEXT,
  father_name   TEXT,
  parent_phone  TEXT,
  class_name    TEXT,
  class_section TEXT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_caller_school UUID;
  v_q             TEXT;
BEGIN

  -- Verify caller is active school_admin of p_school_id
  SELECT p.school_id INTO v_caller_school
  FROM public.profiles p
  WHERE p.id        = auth.uid()
    AND p.school_id = p_school_id
    AND p.role      = 'school_admin'
    AND p.is_active = true;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Access denied';
  END IF;

  v_q := '%' || trim(p_query) || '%';

  RETURN QUERY
  SELECT
    st.id,
    st.full_name::TEXT,
    st.student_uid::TEXT,
    st.father_name::TEXT,
    st.parent_phone::TEXT,
    c.name::TEXT    AS class_name,
    c.section::TEXT AS class_section
  FROM public.students st
  LEFT JOIN public.classes c ON c.id = st.class_id
  WHERE st.school_id = p_school_id
    AND st.is_active = true
    AND (
      st.full_name   ILIKE v_q
      OR st.father_name  ILIKE v_q
      OR st.mother_name  ILIKE v_q
      OR st.parent_phone ILIKE v_q
      OR st.student_uid  ILIKE v_q
    )
    AND (p_class_id IS NULL OR st.class_id = p_class_id)
  ORDER BY
    CASE WHEN st.student_uid ILIKE p_query THEN 0 ELSE 1 END,
    st.full_name
  LIMIT p_limit;

END;
$$;


-- ============================================================
-- SECTION 4: generate_fee_dues_capped()
-- Core due-generation engine with a hard UNTIL-month cap.
-- Dues are NEVER generated beyond p_until_month (current month).
-- Called by auto_generate_monthly_dues() and by the UI button.
--
-- CONFLICTS REMOVED (versions that failed to deploy):
--   v1: v_disc_amount := COALESCE() in DECLARE section — illegal
--   v2: array indexing [v_m] in DECLARE initialiser — illegal
--   THIS (v3): all assignments moved to BEGIN block. FINAL.
-- ============================================================

CREATE OR REPLACE FUNCTION public.generate_fee_dues_capped(
  p_fee_structure_id  UUID,
  p_until_month       TEXT    -- 'YYYY-MM' cap; never generate beyond this
)
RETURNS TABLE (generated_count INTEGER, skipped_count INTEGER)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_structure       RECORD;
  v_item            RECORD;
  v_student         RECORD;
  v_month           TEXT;
  v_due_date        DATE;
  v_disc_amount     NUMERIC(10,2);
  v_net             NUMERIC(10,2);
  v_months          TEXT[];
  v_year_months     TEXT[];
  v_start_year      INTEGER;
  v_m               INTEGER;
  v_generated       INTEGER := 0;
  v_skipped         INTEGER := 0;
BEGIN

  -- Load and validate structure
  SELECT * INTO v_structure
  FROM public.fee_structures
  WHERE id = p_fee_structure_id AND is_active = true;

  IF NOT FOUND THEN
    RETURN QUERY SELECT 0, 0;
    RETURN;
  END IF;

  -- Build all 12 months in the academic year
  v_start_year  := SPLIT_PART(v_structure.academic_year, '-', 1)::INTEGER;
  v_year_months := ARRAY[]::TEXT[];

  FOR v_m IN 0..11 LOOP
    DECLARE
      v_abs_month INTEGER := v_structure.year_start_month + v_m;
      v_y         INTEGER;
      v_mo        INTEGER;
    BEGIN
      v_y  := v_start_year + (v_abs_month - 1) / 12;
      v_mo := ((v_abs_month - 1) % 12) + 1;
      v_year_months := v_year_months ||
        (v_y::TEXT || '-' || LPAD(v_mo::TEXT, 2, '0'));
    END;
  END LOOP;

  -- Loop every enabled fee item in this structure
  FOR v_item IN
    SELECT * FROM public.fee_structure_items
    WHERE fee_structure_id = p_fee_structure_id AND is_enabled = true
    ORDER BY sort_order
  LOOP

    -- Determine applicable months for this item's frequency
    CASE v_item.frequency
      WHEN 'monthly' THEN
        v_months := v_year_months;

      WHEN 'one_time' THEN
        v_months := ARRAY[v_year_months[1]];

      WHEN 'quarterly' THEN
        -- Array indexing must happen in BEGIN, not DECLARE
        DECLARE
          v_qm    INTEGER;
          v_qy    INTEGER;
          v_qarr  INTEGER[];
        BEGIN
          v_qarr   := COALESCE(v_item.quarterly_months, ARRAY[4,7,10,1]);
          v_months := ARRAY[]::TEXT[];
          FOR v_m IN 1..ARRAY_LENGTH(v_qarr, 1) LOOP
            v_qm := v_qarr[v_m];
            IF v_qm >= v_structure.year_start_month THEN
              v_qy := v_start_year;
            ELSE
              v_qy := v_start_year + 1;
            END IF;
            v_months := v_months ||
              (v_qy::TEXT || '-' || LPAD(v_qm::TEXT, 2, '0'));
          END LOOP;
        END;

      WHEN 'custom' THEN
        v_months := COALESCE(v_item.applicable_months, ARRAY[]::TEXT[]);

      ELSE
        v_months := ARRAY[]::TEXT[];
    END CASE;

    -- Loop every active student in this structure's class
    FOR v_student IN
      SELECT s.id AS student_id
      FROM public.students s
      WHERE s.school_id = v_structure.school_id
        AND s.class_id  = v_structure.class_id
        AND s.is_active = true
    LOOP

      -- Get applicable discount for this student + fee_type
      SELECT COALESCE(
        CASE d.discount_type
          WHEN 'percentage' THEN ROUND(v_item.amount * d.value / 100, 2)
          WHEN 'fixed'      THEN LEAST(d.value, v_item.amount)
          ELSE 0
        END, 0
      ) INTO v_disc_amount
      FROM public.fee_discounts d
      WHERE d.student_id  = v_student.student_id
        AND d.school_id   = v_structure.school_id
        AND d.is_active   = true
        AND (d.applies_to_fee_type IS NULL
             OR d.applies_to_fee_type = v_item.fee_type)
        AND (d.valid_from  IS NULL OR d.valid_from  <= CURRENT_DATE)
        AND (d.valid_until IS NULL OR d.valid_until >= CURRENT_DATE)
      ORDER BY d.created_at DESC
      LIMIT 1;

      -- Must check for NULL separately — assignment in SELECT INTO
      -- cannot use := after the statement (causes syntax error 42601)
      IF v_disc_amount IS NULL THEN v_disc_amount := 0; END IF;
      v_net := v_item.amount - v_disc_amount;

      -- Generate a due row for each applicable month
      FOREACH v_month IN ARRAY v_months LOOP

        -- ── KEY RULE: never generate dues beyond current month ──
        CONTINUE WHEN v_month > p_until_month;

        v_due_date := (v_month || '-' ||
          LPAD(v_structure.due_day_of_month::TEXT, 2, '0'))::DATE;

        INSERT INTO public.fee_dues (
          school_id, student_id, fee_structure_id, fee_structure_item_id,
          fee_type, label, month, academic_year, due_date,
          base_amount, discount_amount, net_amount, total_due, status
        ) VALUES (
          v_structure.school_id,
          v_student.student_id,
          p_fee_structure_id,
          v_item.id,
          v_item.fee_type,
          v_item.label,
          v_month,
          v_structure.academic_year,
          v_due_date,
          v_item.amount,
          v_disc_amount,
          v_net,
          v_net,         -- total_due starts equal to net (late fee added later by cron)
          'unpaid'
          -- NOTE: do NOT insert 'balance' — it is a GENERATED ALWAYS column
        )
        ON CONFLICT (student_id, fee_structure_item_id, month) DO NOTHING;

        IF FOUND THEN
          v_generated := v_generated + 1;
        ELSE
          v_skipped := v_skipped + 1;
        END IF;

      END LOOP; -- months

    END LOOP; -- students

  END LOOP; -- items

  RETURN QUERY SELECT v_generated, v_skipped;
END;
$$;


-- ============================================================
-- SECTION 5: auto_generate_monthly_dues()
-- Orchestrator called by pg_cron on 1st of every month.
-- Loops all active fee structures and calls
-- generate_fee_dues_capped() for each, capped at current month.
-- Can also be called with a specific school_id for isolation.
-- ============================================================

CREATE OR REPLACE FUNCTION public.auto_generate_monthly_dues(
  p_school_id UUID DEFAULT NULL
)
RETURNS TABLE (
  school_id        UUID,
  structure_id     UUID,
  structure_name   TEXT,
  generated_count  INTEGER,
  skipped_count    INTEGER
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_structure     RECORD;
  v_current_month TEXT;
  v_result        RECORD;
BEGIN

  v_current_month := TO_CHAR(CURRENT_DATE, 'YYYY-MM');

  FOR v_structure IN
    SELECT fs.id, fs.school_id, fs.name
    FROM public.fee_structures fs
    WHERE fs.is_active = true
      AND (p_school_id IS NULL OR fs.school_id = p_school_id)
    ORDER BY fs.school_id, fs.created_at
  LOOP

    SELECT g.generated_count, g.skipped_count
    INTO v_result
    FROM public.generate_fee_dues_capped(
      v_structure.id,
      v_current_month
    ) g;

    RETURN QUERY SELECT
      v_structure.school_id,
      v_structure.id,
      v_structure.name::TEXT,
      COALESCE(v_result.generated_count, 0),
      COALESCE(v_result.skipped_count,   0);

  END LOOP;

END;
$$;


-- ============================================================
-- SECTION 6: trigger_manual_due_generation()
-- Admin-facing RPC. Verifies caller is school_admin, then
-- runs auto_generate_monthly_dues() for their school only.
-- Called by the "Generate Dues" button on the fees page.
-- ============================================================

CREATE OR REPLACE FUNCTION public.trigger_manual_due_generation()
RETURNS TABLE (
  structure_name  TEXT,
  generated_count INTEGER,
  skipped_count   INTEGER
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_school_id UUID;
BEGIN

  SELECT p.school_id INTO v_school_id
  FROM public.profiles p
  WHERE p.id        = auth.uid()
    AND p.role      = 'school_admin'
    AND p.is_active = true;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Access denied';
  END IF;

  RETURN QUERY
  SELECT r.structure_name, r.generated_count, r.skipped_count
  FROM public.auto_generate_monthly_dues(v_school_id) r;

END;
$$;


-- ============================================================
-- SECTION 7: assign_student_fee_structure()
-- Admin assigns or removes a fee structure package for a student.
-- Pass p_fee_structure_id = NULL to unassign.
-- Validates: caller is school_admin, student and structure
-- both belong to caller's school, structure is active.
-- ============================================================

CREATE OR REPLACE FUNCTION public.assign_student_fee_structure(
  p_student_id       UUID,
  p_fee_structure_id UUID    -- pass NULL to unassign
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_school_id UUID;
BEGIN

  SELECT p.school_id INTO v_school_id
  FROM public.profiles p
  WHERE p.id        = auth.uid()
    AND p.role      = 'school_admin'
    AND p.is_active = true;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Access denied';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.students
    WHERE id = p_student_id AND school_id = v_school_id
  ) THEN
    RAISE EXCEPTION 'Student not found';
  END IF;

  IF p_fee_structure_id IS NOT NULL THEN
    IF NOT EXISTS (
      SELECT 1 FROM public.fee_structures
      WHERE id        = p_fee_structure_id
        AND school_id = v_school_id
        AND is_active = true
    ) THEN
      RAISE EXCEPTION 'Fee structure not found or inactive';
    END IF;
  END IF;

  UPDATE public.students
  SET
    fee_structure_id = p_fee_structure_id,
    updated_at       = NOW()
  WHERE id = p_student_id;

END;
$$;


-- ============================================================
-- SECTION 8: get_student_billing_summary()
-- Single RPC for the billing screen. Returns student info,
-- their assigned fee structure name, all pending/partial dues,
-- and pre-calculated grand totals in one call.
-- Used by the /collect page after student selection.
-- ============================================================

CREATE OR REPLACE FUNCTION public.get_student_billing_summary(
  p_student_id UUID
)
RETURNS TABLE (
  -- Student
  student_id          UUID,
  full_name           TEXT,
  student_uid         TEXT,
  father_name         TEXT,
  parent_phone        TEXT,
  class_name          TEXT,
  class_section       TEXT,
  -- Assigned fee structure
  fee_structure_id    UUID,
  fee_structure_name  TEXT,
  -- Individual pending dues (one row per due)
  due_id              UUID,
  due_label           TEXT,
  due_month           TEXT,
  due_date            DATE,
  total_due           NUMERIC,
  amount_paid         NUMERIC,
  balance             NUMERIC,
  status              TEXT,
  late_fee_applied    BOOLEAN,
  -- Pre-calculated totals across all pending dues
  grand_total_due     NUMERIC,
  grand_total_paid    NUMERIC,
  grand_balance       NUMERIC
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_caller_school UUID;
  v_student_school UUID;
  v_grand_due     NUMERIC;
  v_grand_paid    NUMERIC;
  v_grand_balance NUMERIC;
BEGIN

  SELECT p.school_id INTO v_caller_school
  FROM public.profiles p
  WHERE p.id        = auth.uid()
    AND p.role      = 'school_admin'
    AND p.is_active = true;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Access denied';
  END IF;

  SELECT s.school_id INTO v_student_school
  FROM public.students s
  WHERE s.id = p_student_id;

  IF v_student_school IS DISTINCT FROM v_caller_school THEN
    RAISE EXCEPTION 'Student not found';
  END IF;

  -- Aggregate pending totals
  SELECT
    COALESCE(SUM(d.total_due), 0),
    COALESCE(SUM(d.amount_paid), 0),
    COALESCE(SUM(d.balance), 0)
  INTO v_grand_due, v_grand_paid, v_grand_balance
  FROM public.fee_dues d
  WHERE d.student_id = p_student_id
    AND d.status NOT IN ('paid', 'waived');

  RETURN QUERY
  SELECT
    s.id,
    s.full_name::TEXT,
    s.student_uid::TEXT,
    s.father_name::TEXT,
    s.parent_phone::TEXT,
    c.name::TEXT,
    c.section::TEXT,
    fs.id,
    fs.name::TEXT,
    d.id,
    d.label::TEXT,
    d.month::TEXT,
    d.due_date,
    d.total_due,
    d.amount_paid,
    d.balance,
    d.status::TEXT,
    d.late_fee_applied,
    v_grand_due,
    v_grand_paid,
    v_grand_balance
  FROM public.students s
  LEFT JOIN public.classes c         ON c.id  = s.class_id
  LEFT JOIN public.fee_structures fs ON fs.id = s.fee_structure_id
  LEFT JOIN public.fee_dues d        ON d.student_id = s.id
    AND d.status NOT IN ('paid', 'waived')
  WHERE s.id = p_student_id
  ORDER BY d.due_date ASC NULLS LAST;

END;
$$;


-- ============================================================
-- SECTION 9: PERMISSIONS
-- Revoke public access and grant to correct roles.
-- Applied to every new/replaced function in this migration.
-- ============================================================

-- record_fee_payment — authenticated users only (school_admin validated inside)
REVOKE ALL ON FUNCTION public.record_fee_payment(UUID,UUID,UUID,NUMERIC,TEXT,DATE,UUID,TEXT) FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION public.record_fee_payment(UUID,UUID,UUID,NUMERIC,TEXT,DATE,UUID,TEXT) TO authenticated;

-- search_students_omnibox — authenticated users only
REVOKE ALL ON FUNCTION public.search_students_omnibox(UUID,TEXT,UUID,INT) FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION public.search_students_omnibox(UUID,TEXT,UUID,INT) TO authenticated;

-- generate_fee_dues_capped — authenticated + service_role (called by cron via auto_generate)
REVOKE ALL ON FUNCTION public.generate_fee_dues_capped(UUID,TEXT) FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION public.generate_fee_dues_capped(UUID,TEXT) TO authenticated;
GRANT  EXECUTE ON FUNCTION public.generate_fee_dues_capped(UUID,TEXT) TO service_role;

-- auto_generate_monthly_dues — authenticated + service_role (pg_cron runs as service_role)
REVOKE ALL ON FUNCTION public.auto_generate_monthly_dues(UUID) FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION public.auto_generate_monthly_dues(UUID) TO authenticated;
GRANT  EXECUTE ON FUNCTION public.auto_generate_monthly_dues(UUID) TO service_role;

-- trigger_manual_due_generation — authenticated only (school_admin validated inside)
REVOKE ALL ON FUNCTION public.trigger_manual_due_generation() FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION public.trigger_manual_due_generation() TO authenticated;

-- assign_student_fee_structure — authenticated only
REVOKE ALL ON FUNCTION public.assign_student_fee_structure(UUID,UUID) FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION public.assign_student_fee_structure(UUID,UUID) TO authenticated;

-- get_student_billing_summary — authenticated only
REVOKE ALL ON FUNCTION public.get_student_billing_summary(UUID) FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION public.get_student_billing_summary(UUID) TO authenticated;


-- ============================================================
-- SECTION 10: pg_cron JOB
-- Monthly auto-generation of fee dues.
-- Fires at 19:00 UTC = 00:30 IST on the 1st of every month.
-- Safe unschedule: uses DO block to check existence first.
-- CONFLICT REMOVED: first attempt used invalid
--   SELECT cron.unschedule() WHERE EXISTS — not valid SQL.
--   Final version uses DO $$ IF EXISTS THEN PERFORM $$ pattern.
-- ============================================================

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM cron.job WHERE jobname = 'auto-generate-monthly-dues'
  ) THEN
    PERFORM cron.unschedule('auto-generate-monthly-dues');
  END IF;
END $$;

SELECT cron.schedule(
  'auto-generate-monthly-dues',
  '0 19 1 * *',    -- 19:00 UTC = 00:30 IST on 1st of every month
  $$
    SELECT public.auto_generate_monthly_dues(NULL);
  $$
);

-- ============================================================
-- END OF MIGRATION
-- Verify with:
--   SELECT * FROM cron.job WHERE jobname = 'auto-generate-monthly-dues';
--   SELECT column_name FROM information_schema.columns
--     WHERE table_name = 'students' AND column_name = 'fee_structure_id';
--   SELECT proname FROM pg_proc WHERE proname LIKE '%omnibox%'
--     OR proname LIKE '%billing_summary%'
--     OR proname LIKE '%dues_capped%';
-- ============================================================
