-- ============================================================
-- SCHOOLIUM — Sprint 3 Step 1
-- UNIFY BILLING: Drop fees table, extend fee_dues for manual billing
-- File: sprint3_step1_unify_billing.sql
-- Run ONCE in Supabase SQL Editor (production)
-- No customer data exists — safe to drop fees table
-- ============================================================
--
-- WHAT THIS DOES:
--   1. Drop the fees table (and all its indexes, policies, references)
--   2. ALTER fee_dues:
--        ADD source        TEXT  'structured' | 'manual'  (default 'structured')
--        ADD collected_at_billing BOOLEAN  (true = paid immediately at time of entry)
--        DROP CONSTRAINT fee_dues_unique_per_month  (manual dues have no structure item)
--        ADD  CONSTRAINT fee_dues_structured_unique (only applies when source='structured')
--        Make fee_structure_id    NULLABLE (manual dues have no structure)
--        Make fee_structure_item_id NULLABLE (manual dues have no item)
--        ADD admin_label TEXT (human label for manual dues, overrides label column)
--   3. Rebuild get_student_fee_ledger() — remove fees join, use fee_dues.source
--   4. Rebuild get_defaulters()         — already only queries fee_dues, no change needed
--   5. Rebuild get_fee_dashboard_stats() — remove fees queries, pure fee_payments
--   6. Rebuild get_student_billing_summary() — already only queries fee_dues, no change needed
--   7. New RPC: create_manual_due() — admin creates ad-hoc dues on the spot
--   8. Update RLS on fee_dues — ensure manual dues follow same school_id pattern
--   9. REVOKE / GRANT on new function
-- ============================================================


-- ============================================================
-- STEP 1: DROP fees TABLE (clean — no customer data)
-- ============================================================

-- Drop RLS policies first
DROP POLICY IF EXISTS "school_sees_own_fees"      ON public.fees;
DROP POLICY IF EXISTS "super_admin_sees_all_fees" ON public.fees;

-- Drop indexes
DROP INDEX IF EXISTS public.idx_fees_school_id;
DROP INDEX IF EXISTS public.idx_fees_student_id;
DROP INDEX IF EXISTS public.idx_fees_status;

-- Drop the table
DROP TABLE IF EXISTS public.fees CASCADE;


-- ============================================================
-- STEP 2: EXTEND fee_dues FOR MANUAL BILLING
-- ============================================================

-- 2a. Add source column — 'structured' (auto-generated) or 'manual' (admin created)
ALTER TABLE public.fee_dues
  ADD COLUMN IF NOT EXISTS source TEXT NOT NULL DEFAULT 'structured'
    CHECK (source IN ('structured', 'manual'));

-- 2b. Make fee_structure_id nullable — manual dues have no structure
ALTER TABLE public.fee_dues
  ALTER COLUMN fee_structure_id DROP NOT NULL;

-- 2c. Make fee_structure_item_id nullable — manual dues have no item
ALTER TABLE public.fee_dues
  ALTER COLUMN fee_structure_item_id DROP NOT NULL;

-- 2d. Expand fee_type check — add hostel, admission, other already exist but
--     also add 'miscellaneous' as a catch-all for admin
ALTER TABLE public.fee_dues
  DROP CONSTRAINT IF EXISTS fee_dues_fee_type_check;

-- No CHECK on fee_type — let it be freeform text for manual dues
-- Structured dues use the item's fee_type which is already validated at structure level

-- 2e. DROP the old unique constraint that required fee_structure_item_id
--     (it would block manual dues which have NULL fee_structure_item_id)
ALTER TABLE public.fee_dues
  DROP CONSTRAINT IF EXISTS fee_dues_unique_per_month;

-- 2f. ADD partial unique constraint: only one structured due per student/item/month
--     Manual dues (source='manual') are exempt — admin can add as many as needed
CREATE UNIQUE INDEX IF NOT EXISTS fee_dues_structured_unique
  ON public.fee_dues (student_id, fee_structure_item_id, month)
  WHERE source = 'structured' AND fee_structure_item_id IS NOT NULL;

-- 2g. Add label column for manual dues — freeform admin description
--     (label column already exists, we just ensure it accepts manual values)
--     Add academic_year default for manual dues (current school year)
--     No schema change needed — label is already TEXT NOT NULL

-- 2h. Update table comment to reflect unified purpose
COMMENT ON TABLE public.fee_dues IS
  'Unified fee dues table. source=''structured'' for auto-generated monthly dues from fee_structures. '
  'source=''manual'' for admin-created ad-hoc dues (replaces the old fees table). '
  'balance is GENERATED ALWAYS AS (total_due - amount_paid) — never update directly. '
  'record_fee_payment() is the only way to record payments.';

COMMENT ON COLUMN public.fee_dues.source IS
  '''structured'' = auto-generated by generate_fee_dues_capped(). '
  '''manual'' = created by admin via create_manual_due() RPC.';


-- ============================================================
-- STEP 3: create_manual_due() — NEW RPC
-- Admin creates an ad-hoc fee due for a student.
-- Optionally collects payment immediately (at billing time).
-- Multiple fee types supported — call once per line item.
-- ============================================================

CREATE OR REPLACE FUNCTION public.create_manual_due(
  p_school_id      UUID,
  p_student_id     UUID,
  p_fee_type       TEXT,         -- e.g. 'tuition', 'exam', 'transport', 'hostel', 'admission', 'other'
  p_label          TEXT,         -- display label e.g. 'Tuition Fee - June 2026'
  p_amount         NUMERIC(10,2),
  p_due_date       DATE,
  p_month          TEXT,         -- 'YYYY-MM' e.g. '2026-06'
  p_academic_year  TEXT,         -- e.g. '2025-26'
  p_notes          TEXT DEFAULT NULL
)
RETURNS TABLE (due_id UUID)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_due_id  UUID;
BEGIN

  -- ── Auth: must be active school_admin for this school ──
  IF NOT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id        = auth.uid()
      AND school_id = p_school_id
      AND role      = 'school_admin'
      AND is_active = true
  ) THEN
    RAISE EXCEPTION 'Access denied — school_admin role required';
  END IF;

  -- ── Validate student belongs to this school ──
  IF NOT EXISTS (
    SELECT 1 FROM public.students
    WHERE id        = p_student_id
      AND school_id = p_school_id
      AND is_active = true
  ) THEN
    RAISE EXCEPTION 'Student not found or not active in this school';
  END IF;

  -- ── Validate amount ──
  IF p_amount IS NULL OR p_amount <= 0 THEN
    RAISE EXCEPTION 'Amount must be greater than zero';
  END IF;

  -- ── Insert manual due ──
  INSERT INTO public.fee_dues (
    school_id,
    student_id,
    fee_structure_id,       -- NULL for manual
    fee_structure_item_id,  -- NULL for manual
    source,
    fee_type,
    label,
    month,
    academic_year,
    due_date,
    base_amount,
    discount_amount,
    net_amount,
    late_fee_amount,
    total_due,
    amount_paid,
    status,
    notes
  ) VALUES (
    p_school_id,
    p_student_id,
    NULL,                   -- no structure
    NULL,                   -- no structure item
    'manual',
    p_fee_type,
    p_label,
    p_month,
    p_academic_year,
    p_due_date,
    p_amount,               -- base = full amount (no discount on manual)
    0,                      -- no discount
    p_amount,               -- net = base
    0,                      -- no late fee at creation
    p_amount,               -- total_due = amount
    0,                      -- amount_paid starts at 0
    'unpaid',
    p_notes
  )
  RETURNING id INTO v_due_id;

  RETURN QUERY SELECT v_due_id;

END;
$$;

-- Permissions
REVOKE ALL ON FUNCTION public.create_manual_due(
  UUID, UUID, TEXT, TEXT, NUMERIC, DATE, TEXT, TEXT, TEXT
) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.create_manual_due(
  UUID, UUID, TEXT, TEXT, NUMERIC, DATE, TEXT, TEXT, TEXT
) TO authenticated;


-- ============================================================
-- STEP 4: REBUILD get_student_fee_ledger()
-- Remove all references to the fees table.
-- Manual dues now come from fee_dues WHERE source = 'manual'.
-- ============================================================

CREATE OR REPLACE FUNCTION public.get_student_fee_ledger(
  p_school_id  UUID,
  p_student_id UUID
)
RETURNS TABLE (
  due_id             UUID,
  source             TEXT,
  fee_type           TEXT,
  label              TEXT,
  month              TEXT,
  academic_year      TEXT,
  due_date           DATE,
  base_amount        NUMERIC,
  discount_amount    NUMERIC,
  net_amount         NUMERIC,
  late_fee_amount    NUMERIC,
  total_due          NUMERIC,
  amount_paid        NUMERIC,
  balance            NUMERIC,
  status             TEXT,
  late_fee_applied   BOOLEAN,
  payments_count     BIGINT,
  last_payment_date  DATE,
  last_receipt       TEXT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN

  -- ── Auth: school_admin only ──
  IF NOT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id        = auth.uid()
      AND school_id = p_school_id
      AND role      = 'school_admin'
      AND is_active = true
  ) THEN
    RAISE EXCEPTION 'Access denied — school_admin role required';
  END IF;

  RETURN QUERY
  SELECT
    d.id                                        AS due_id,
    d.source,
    d.fee_type,
    d.label,
    d.month,
    d.academic_year,
    d.due_date,
    d.base_amount,
    d.discount_amount,
    d.net_amount,
    d.late_fee_amount,
    d.total_due,
    d.amount_paid,
    d.balance,
    d.status,
    d.late_fee_applied,
    COUNT(fp.id)                                AS payments_count,
    MAX(fp.paid_date)                           AS last_payment_date,
    MAX(fp.receipt_number)                      AS last_receipt
  FROM public.fee_dues d
  LEFT JOIN public.fee_payments fp ON fp.fee_due_id = d.id
  WHERE d.school_id  = p_school_id
    AND d.student_id = p_student_id
  GROUP BY
    d.id, d.source, d.fee_type, d.label, d.month,
    d.academic_year, d.due_date, d.base_amount,
    d.discount_amount, d.net_amount, d.late_fee_amount,
    d.total_due, d.amount_paid, d.balance,
    d.status, d.late_fee_applied
  ORDER BY d.due_date DESC, d.created_at DESC;

END;
$$;

-- Permissions
REVOKE ALL ON FUNCTION public.get_student_fee_ledger(UUID, UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_student_fee_ledger(UUID, UUID) TO authenticated;


-- ============================================================
-- STEP 5: REBUILD get_fee_dashboard_stats()
-- Remove fees table queries — everything from fee_payments now.
-- ============================================================

CREATE OR REPLACE FUNCTION public.get_fee_dashboard_stats(p_school_id UUID)
RETURNS TABLE (
  today_collection    NUMERIC,
  month_collection    NUMERIC,
  total_pending       NUMERIC,
  defaulters_count    BIGINT,
  total_collected_ytd NUMERIC
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN QUERY
  SELECT
    -- Today's total collection (all sources via fee_payments)
    COALESCE((
      SELECT SUM(fp.amount_paid)
      FROM public.fee_payments fp
      WHERE fp.school_id = p_school_id
        AND fp.paid_date = CURRENT_DATE
    ), 0::NUMERIC),

    -- This calendar month's total collection
    COALESCE((
      SELECT SUM(fp.amount_paid)
      FROM public.fee_payments fp
      WHERE fp.school_id = p_school_id
        AND TO_CHAR(fp.paid_date, 'YYYY-MM') = TO_CHAR(CURRENT_DATE, 'YYYY-MM')
    ), 0::NUMERIC),

    -- Total outstanding balance — ALL dues (structured + manual)
    COALESCE((
      SELECT SUM(d.balance)
      FROM public.fee_dues d
      WHERE d.school_id  = p_school_id
        AND d.status     IN ('unpaid', 'partial')
        AND d.balance    > 0
    ), 0::NUMERIC),

    -- Defaulters count — students with any unpaid/partial due
    COALESCE((
      SELECT COUNT(DISTINCT d.student_id)
      FROM public.fee_dues d
      WHERE d.school_id  = p_school_id
        AND d.status     IN ('unpaid', 'partial')
        AND d.balance    > 0
        AND d.due_date   < CURRENT_DATE
    ), 0::BIGINT),

    -- Year-to-date collection (calendar year)
    COALESCE((
      SELECT SUM(fp.amount_paid)
      FROM public.fee_payments fp
      WHERE fp.school_id = p_school_id
        AND EXTRACT(YEAR FROM fp.paid_date) = EXTRACT(YEAR FROM CURRENT_DATE)
    ), 0::NUMERIC);

END;
$$;

-- Permissions
REVOKE ALL ON FUNCTION public.get_fee_dashboard_stats(UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_fee_dashboard_stats(UUID) TO authenticated;


-- ============================================================
-- STEP 6: REBUILD get_student_billing_summary()
-- Already only queries fee_dues — just add source to the return.
-- ============================================================

CREATE OR REPLACE FUNCTION public.get_student_billing_summary(
  p_student_id UUID
)
RETURNS TABLE (
  student_id          UUID,
  full_name           TEXT,
  student_uid         TEXT,
  father_name         TEXT,
  parent_phone        TEXT,
  class_name          TEXT,
  class_section       TEXT,
  fee_structure_id    UUID,
  fee_structure_name  TEXT,
  source              TEXT,
  due_id              UUID,
  due_label           TEXT,
  due_month           TEXT,
  due_date            DATE,
  total_due           NUMERIC,
  amount_paid         NUMERIC,
  balance             NUMERIC,
  status              TEXT,
  late_fee_applied    BOOLEAN,
  grand_total_due     NUMERIC,
  grand_total_paid    NUMERIC,
  grand_balance       NUMERIC
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_school_id UUID;
BEGIN

  -- ── Get school_id from calling admin's profile ──
  SELECT p.school_id INTO v_school_id
  FROM public.profiles p
  WHERE p.id        = auth.uid()
    AND p.role      = 'school_admin'
    AND p.is_active = true;

  IF v_school_id IS NULL THEN
    RAISE EXCEPTION 'Access denied — school_admin role required';
  END IF;

  RETURN QUERY
  SELECT
    s.id                                          AS student_id,
    s.full_name,
    s.student_uid,
    s.father_name,
    s.parent_phone,
    c.name                                        AS class_name,
    c.section                                     AS class_section,
    d.fee_structure_id,
    fs.name                                       AS fee_structure_name,
    d.source,
    d.id                                          AS due_id,
    d.label                                       AS due_label,
    d.month                                       AS due_month,
    d.due_date,
    d.total_due,
    d.amount_paid,
    d.balance,
    d.status,
    d.late_fee_applied,
    -- Grand totals as window aggregates
    SUM(CASE WHEN d.status IN ('unpaid','partial','paid') THEN d.total_due  ELSE 0 END)
      OVER (PARTITION BY s.id)                    AS grand_total_due,
    SUM(d.amount_paid)
      OVER (PARTITION BY s.id)                    AS grand_total_paid,
    SUM(CASE WHEN d.status IN ('unpaid','partial') THEN d.balance ELSE 0 END)
      OVER (PARTITION BY s.id)                    AS grand_balance
  FROM public.students s
  JOIN public.fee_dues d      ON d.student_id = s.id
  LEFT JOIN public.classes c  ON c.id         = s.class_id
  LEFT JOIN public.fee_structures fs ON fs.id = d.fee_structure_id
  WHERE s.id         = p_student_id
    AND d.school_id  = v_school_id
    AND d.status    IN ('unpaid', 'partial')
    AND d.balance    > 0
  ORDER BY d.due_date ASC, d.source ASC, d.created_at ASC;

END;
$$;

-- Permissions
REVOKE ALL ON FUNCTION public.get_student_billing_summary(UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_student_billing_summary(UUID) TO authenticated;


-- ============================================================
-- STEP 7: UPDATE get_defaulters() — add source awareness
-- Already queries only fee_dues — just ensure manual dues included.
-- (No schema change needed — WHERE clause already covers all sources)
-- Re-run to ensure it's the canonical deployed version.
-- ============================================================

CREATE OR REPLACE FUNCTION public.get_defaulters(
  p_school_id     UUID,
  p_class_id      UUID DEFAULT NULL,
  p_academic_year TEXT DEFAULT NULL
)
RETURNS TABLE (
  student_id      UUID,
  full_name       TEXT,
  student_uid     TEXT,
  class_name      TEXT,
  class_section   TEXT,
  total_balance   NUMERIC,
  oldest_due_date DATE,
  days_overdue    INTEGER,
  dues_count      BIGINT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN

  IF NOT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id        = auth.uid()
      AND school_id = p_school_id
      AND role      = 'school_admin'
      AND is_active = true
  ) THEN
    RAISE EXCEPTION 'Access denied — school_admin role required';
  END IF;

  RETURN QUERY
  SELECT
    s.id,
    s.full_name,
    s.student_uid,
    c.name                              AS class_name,
    c.section                           AS class_section,
    SUM(d.balance)                      AS total_balance,
    MIN(d.due_date)                     AS oldest_due_date,
    (CURRENT_DATE - MIN(d.due_date))    AS days_overdue,
    COUNT(d.id)                         AS dues_count
  FROM public.students s
  JOIN public.fee_dues d     ON d.student_id = s.id
  LEFT JOIN public.classes c ON c.id         = s.class_id
  WHERE d.school_id   = p_school_id
    AND d.status      IN ('unpaid', 'partial')
    AND d.balance     > 0
    AND d.due_date    < CURRENT_DATE
    AND (p_class_id      IS NULL OR s.class_id      = p_class_id)
    AND (p_academic_year IS NULL OR d.academic_year = p_academic_year)
  GROUP BY s.id, s.full_name, s.student_uid, c.name, c.section
  ORDER BY total_balance DESC;

END;
$$;

REVOKE ALL ON FUNCTION public.get_defaulters(UUID, UUID, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_defaulters(UUID, UUID, TEXT) TO authenticated;


-- ============================================================
-- STEP 8: RLS on fee_dues — ensure manual dues covered
-- Existing policies already use school_id scoping — safe.
-- Re-run to be explicit.
-- ============================================================

-- Drop and recreate to be safe
DROP POLICY IF EXISTS "school_sees_own_dues"       ON public.fee_dues;
DROP POLICY IF EXISTS "super_admin_sees_all_dues"  ON public.fee_dues;

-- School admin sees only their school's dues (structured + manual)
CREATE POLICY "school_sees_own_dues"
  ON public.fee_dues FOR ALL
  USING (
    school_id IN (
      SELECT p.school_id FROM public.profiles p
      WHERE p.id = auth.uid() AND p.is_active = true
    )
  );

-- Super admin sees everything
CREATE POLICY "super_admin_sees_all_dues"
  ON public.fee_dues FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid() AND p.role = 'super_admin' AND p.is_active = true
    )
  );


-- ============================================================
-- STEP 9: Index for manual due queries
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_fee_dues_source
  ON public.fee_dues(school_id, source);

CREATE INDEX IF NOT EXISTS idx_fee_dues_student_source
  ON public.fee_dues(student_id, source, status);


-- ============================================================
-- VERIFICATION QUERIES
-- Run these after migration to confirm everything is clean.
-- ============================================================
--
-- 1. Confirm fees table is gone:
--    SELECT to_regclass('public.fees');  -- should return NULL
--
-- 2. Confirm fee_dues new columns:
--    SELECT column_name, data_type, is_nullable
--    FROM information_schema.columns
--    WHERE table_name = 'fee_dues'
--    ORDER BY ordinal_position;
--
-- 3. Confirm new functions exist:
--    SELECT routine_name FROM information_schema.routines
--    WHERE routine_schema = 'public'
--    AND routine_name IN (
--      'create_manual_due',
--      'get_student_fee_ledger',
--      'get_fee_dashboard_stats',
--      'get_student_billing_summary',
--      'get_defaulters'
--    );
--
-- 4. Test create_manual_due (replace UUIDs):
--    SELECT * FROM create_manual_due(
--      'your-school-id'::uuid,
--      'your-student-id'::uuid,
--      'tuition', 'Tuition Fee - June 2026',
--      5000, '2026-06-30', '2026-06', '2025-26'
--    );
-- ============================================================

